version: '3.8'

services:
  bookarchive:
    image: bookarchive
    build:
      context: .
      dockerfile: BookArchive/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=BookArchive;User=root;Password=;  # Update connection string

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: BookArchive
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"  # Exposes MySQL on port 3306
    volumes:
      - db_data:/var/lib/mysql  # Persists data

volumes:
  db_data:
